/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardFlightsRouteImport } from './routes/dashboard/flights'
import { Route as DashboardGatesRouteImport } from './routes/dashboard/gates'
import { Route as DashboardResourcesRouteImport } from './routes/dashboard/resources'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFlightsRoute = DashboardFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGatesRoute = DashboardGatesRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResourcesRoute = DashboardResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/flights': typeof DashboardFlightsRoute
  '/dashboard/gates': typeof DashboardGatesRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/flights': typeof DashboardFlightsRoute
  '/dashboard/gates': typeof DashboardGatesRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/flights': typeof DashboardFlightsRoute
  '/dashboard/gates': typeof DashboardGatesRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/flights'
    | '/dashboard/gates'
    | '/dashboard/resources'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/flights'
    | '/dashboard/gates'
    | '/dashboard/resources'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/flights'
    | '/dashboard/gates'
    | '/dashboard/resources'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/flights': {
      id: '/dashboard/flights'
      path: '/flights'
      fullPath: '/dashboard/flights'
      preLoaderRoute: typeof DashboardFlightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gates': {
      id: '/dashboard/gates'
      path: '/gates'
      fullPath: '/dashboard/gates'
      preLoaderRoute: typeof DashboardGatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resources': {
      id: '/dashboard/resources'
      path: '/resources'
      fullPath: '/dashboard/resources'
      preLoaderRoute: typeof DashboardResourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardFlightsRoute: typeof DashboardFlightsRoute
  DashboardGatesRoute: typeof DashboardGatesRoute
  DashboardResourcesRoute: typeof DashboardResourcesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFlightsRoute: DashboardFlightsRoute,
  DashboardGatesRoute: DashboardGatesRoute,
  DashboardResourcesRoute: DashboardResourcesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
